applications = [
  # System
  "linux",                       # Kernel
  "linux-firmware",              # Firmware
  "base",                        # Core utilities
  "sddm",                        # Display manager
  "hyprland",                    # Wayland compositor
  "uwsm",                        # Wayland compositor manager
  "xorg-xwayland",               # X11 compatibility layer for Wayland
  "xdg-desktop-portal",          # XDG desktop portal
  "xdg-desktop-portal-hyprland", # XDG desktop portal

  # Shells
  "nushell",
  "zsh",
  "bash",

  # Key mapper
  "keyd",

  # Fonts
  "ttf-firacode-nerd",

  # CLIs
  "xdg-utils",         # XDG MIME application manager
  "xdg-user-dirs",     # XDG user directory manager
  "wl-clipboard-rs",   # Clipboard manager
  "usage",             # UI toolkit
  "gum",               # Specification for parsing arguments
  "mise",              # Tool version manager
  "jujutsu",           # VCS
  "gitoxide",          # VCS
  "git",               # VCS
  "git-absorb",        # Git plugin
  "git-flow-next",     # Git plugin
  "just",              # Command runner
  "chezmoi",           # Dotfile manager
  "zoxide",            # Change directory
  "eza",               # List files
  "bat",               # View files
  "bat-extras",        # Bat utilities
  "fd",                # Find files
  "ripgrep",           # Search files
  "ripgrep-all",       # Ripgrep utilities
  "git-delta",         # Compare files
  "difftastic",        # Compare files
  "sd",                # Search and replace files
  "choose",            # Extract text from files
  "rust-parallel-bin", # Parse arguments and execute commands
  "pueue",             # Background task executor
  "watchexec",         # File watcher
  "scc-bin",           # Code counter
  "hyperfine",         # Benchmarking
  "procs",             # View running processes
  "ouch",              # Compress and decompress files
  "age",               # Encryption
  "sops",              # Configuration file encryption
  "gojq-bin",          # JSON toolkit
  "taplo",             # TOML toolkit
  "go-yq",             # JSON, TOML, YAML, XML and CSV toolkit
  "precious",          # Linter and formatter
  "lefthook-bin",      # Git hook manager
  "tree-sitter-cli",   # Treesitter parser generator
  "xh",                # HTTP client
  "less",              # Pager
  "make",              # Build system
  "gnupg",             # Encryption and signing
  "zk",                # Note taker
  "dstask",            # To do manager
  "task",              # To do manager
  "timew",             # Time tracker
  "rustledger",        # Accounting
  "beanquery",         # Beancount query tool
  "d2",                # Diagram as code
  "mermaid-cli",       # Diagram as code
  "presenterm",        # Presentation as code
  "marp-cli",          # Presentation as code
  "rclone",            # Cloud storage
  "github-cli",        # GitHub client
  "jira-cli",          # Jira client
  "playwright",        # Browser automation
  "podman",            # Containerization
  "podman-compose",    # Podman plugin
  "colima-bin",        # Containerization
  "docker",            # Containerization
  "docker-compose",    # Docker plugin
  "docker-buildx",     # Docker plugin
  "kubectl",           # Container orchestration
  "helm",              # Kubernetes package manager
  "stern",             # Kubernetes log explorer
  "kubectx",           # Kubernetes context manager
  "kubens",            # Kubernetes namespace manager
  "postgresql",        # SQL database
  "redis",             # Key value database

  # TUIs
  "jjui",            # Jujutsu client
  "fzf",             # Fuzzy finder
  "television",      # Fuzzy finder
  "yazi",            # File system explorer
  "neovim",          # Text editor
  "lazygit",         # Git client
  "zellij",          # Terminal multiplexer
  "bottom",          # System monitor
  "taskwarrior-tui", # Taskwarrior client
  "jiratui",         # Jira client
  "podman-tui-bin",  # Podman client
  "lazydocker",      # Docker client
  "k9s",             # Kubernetes client

  # GUIs
  "walker-bin",                # Application launcher
  "elephant-all-bin",          # Application launcher
  "chromium",                  # Browser
  "brave-bin",                 # Browser
  "firefox",                   # Browser
  "firefox-developer-edition", # Browser
  "browseros-bin",             # Browser
  "zen-browser",               # Browser
  "helium-browser",            # Browser
  "xdg-terminal-exec",         # Terminal
  "ghostty",                   # Terminal
  "wezterm",                   # Terminal
  "alacritty",                 # Terminal
  "waveterm-bin",              # Terminal
  "cmux",                      # Terminal
  "emacs",                     # Text editor
  "vscodium",                  # Text editor
  "zed",                       # Text editor
  "void-bin",                  # Text editor
  "logseq",                    # Note taker
  "affine",                    # Note taker
  "anytype",                   # Note taker
  "appflowy",                  # Note taker
  "element-desktop",           # Instant messenger
  "signal-desktop",            # Instant messenger
  "telegram-desktop",          # Instant messenger
  "proton-pass-bin",           # Password manager
  "bruno",                     # API client
  "insomnia",                  # API client
  "dbeaver",                   # DB client
  # TODO: Proton drive
  # TODO: Proton VPN
  # Proprietary
  "google-chrome",          # Browser
  "warp-terminal-bin",      # Terminal
  "visual-studio-code-bin", # Text editor
  "antigravity",            # Text editor
  "cursor",                 # Text editor
  "windsurf",               # Text editor
  "obsidian",               # Note taker
  "notion-app-electron",    # Note taker
  "postman-bin",            # API client
  "discord",                # Instant messenger
  "slack",                  # Instant messenger
  "whatsapp-for-linux",     # Instant messenger
  "zoom",                   # Video caller

  # WUIs
  "fava", # Beancount client

  # Shell utilities
  "sheldon",          # Bash and Zsh plugin manager
  "zinit",            # Zsh plugin manager
  "starship",         # Prompt
  "atuin",            # History
  "blesh",            # Line editor
  "carapace-bin",     # Autocompletion
  "pay-respects-bin", # Autocorrection

  # AI utilities
  "rtk",                     # LLM token reducer
  "ollama",                  # Local LLM manager
  "aichat",                  # AI agent
  "aider-chat",              # AI agent
  "opencode-bin",            # AI agent
  "gemini-cli",              # AI agent
  "github-copilot-cli",      # AI agent
  "openai-codex-bin",        # AI agent
  "openwork",                # AI agent
  "anythingllm-desktop-bin", # AI agent
  "opencode-desktop-bin ",   # AI agent
  "t3-code-bin",             # AI agent
  # Proprietary
  "lmstudio-beta",      # AI agent TODO: Upgrade from beta
  "claude-code",        # AI agent
  "cursor-cli",         # AI agent
  "claude-desktop-bin", # AI agent

  # Bash
  "bash-language-server", # Language server
  "shellcheck",           # Linter
  "shfmt",                # Formatter

  # Beancount
  "beancount",                 # Linter and formatter
  "beancount-language-server", # Language server

  # Typst
  "typst",

  # Lua
  "lua-language-server", # Language server
  "luacheck",            # Linter
  "stylua",              # Formatter

  # Fennel
  "fennel",
  "fennel-ls", # Language server
  "fnlfmt",    # Formatter

  # Haskell
  "ghc",
  "stack",                   # Version manager, package manager, project manager, command runner and binary installer
  "haskell-language-server", # Language server
  "hlint",                   # Linter
  "haskell-fourmolu",        # Formatter

  # Rust
  "rust",
  "cargo-binstall", # Binary installer
  "rust-analyzer",  # Language server

  # Go
  "go",
  "gopls",       # Language server
  "staticcheck", # Linter
  "gofumpt",     # Formatter
  "delve",       # Debugger
  "mockery-bin", # Mock generator
  "migrate",     # Migration manager

  # JavaScript
  "nodejs",
  "deno",
  "bun-bin",
  "pnpm",    # Version manager, package manager, project manager, command runner and binary installer
  "vite",    # Build tool
  "biome",   # Language server, linter and formatter

  # Python
  "python",
  "uv",     # Version manager, package manager, project manager, command runner and binary installer
  "ty-bin", # Type checker and language server
  "ruff",   # Linter and formatter
]
