#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Upgrade Emacs packages
main() {
	emacs --batch --load=~/.config/emacs/init.el --eval='(progn (elpaca-pull-all) (elpaca-wait))'
}

main "$@"
