#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Install Paru applications
main() {
	local paru_file=~/.config/paru.toml
	[[ -f "$paru_file" ]] &&
		yq '.applications[]' "$paru_file" |
		paru --sync --needed --noconfirm -
}

main "$@"
