#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Install Arch Linux package manager
main() {
	command -v paru &>/dev/null || return
	local paru_dir
	paru_dir="$(mktemp --directory)"
	trap 'rm -r "$paru_dir"' RETURN
	git clone https://aur.archlinux.org/paru.git "$paru_dir"
	cd "$paru_dir"
	makepkg --install --syncdeps --noconfirm
	cd -
}

main "$@"
