#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Sync Homebrew applications
main() {
	# TODO: Check if --force is required
	[[ -f ~/.Brewfile ]] && brew bundle install --global
}

main "$@"
