#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Link Doomemacs GUI
main() {
	echo 'do shell script "open -na Emacs.app --args --init-directory=~/.config/doomemacs"' | osacompile -o /Applications/Doomemacs.app
}

main "$@"
